### ISSUE TITLE
Autoclose?

### ISSUE THREAD

**Issue by yayanbachtiar** [T00rk/bootstrap-material-datetimepicker#67]
how to autoclose this datepicker?

**Comment by p-Enzi** [comment]
Yes, this is why I dont use this picker.
You have to do double the clicks on every simple selection: 
First a value and then OK.
So to choose a simple time-value you have to click 4!! times instead of simple two numbers.
The Material design would be perfect to choose a time - 
but in this case it is not very comfortable with this OK OK OK OK ...

**Comment by T00rk** [comment]
I added a **switchOnClick** param for that
